name: E2E Chrome

on:
  workflow_call:
    secrets:
      PR_COMMENT_TOKEN:
        required: true

jobs:
  test-e2e-chrome-solana:
    uses: ./.github/workflows/run-e2e.yml
    with:
      test-suite-name: test-e2e-chrome-solana
      build-artifact: prep-build-test-flask-browserify-chrome
      build-command: yarn build:test:flask
      test-command: yarn test:e2e:single test/e2e/flask/solana-wallet-standard --browser chrome

  test-e2e-chrome-report:
    needs:
      - test-e2e-chrome-solana
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ github.repository_owner }}
      REPOSITORY: ${{ github.event.repository.name }}
      BRANCH: ${{ github.head_ref || github.ref_name }}
      TEST_RUNS_PATH: test/test-results/test-runs-chrome.json
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: test-e2e-chrome*
          merge-multiple: true

      - name: Create test report
        run: yarn tsx .github/scripts/create-e2e-test-report.ts

      - name: Upload test runs
        uses: actions/upload-artifact@v4
        with:
          name: test-e2e-chrome-report
          path: ${{ env.TEST_RUNS_PATH }}
