name: Main

on:
  push:
    branches:
      - main
      - master
      - Version-v*
      - trigger-ci*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

env:
  # For a `pull_request` event, the branch is `github.head_ref``.
  # For a `push` event, the branch is `github.ref_name`.
  BRANCH: ${{ github.head_ref || github.ref_name }}
  # For a `pull_request` event, the fork is `github.event.pull_request.head.repo.fork`.
  # For a `push` event, the fork is `github.event.repository.fork`.
  IS_FORK: ${{ github.event.pull_request.head.repo.fork || github.event.repository.fork }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !(contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/master')) }}

jobs:
  prep-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          cache-node-modules: true
          skip-allow-scripts: true

  prep-build-test-flask:
    needs:
      - prep-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - run: yarn build:test:flask

      - name: Upload artifact prep-build-test-flask-browserify-chrome
        uses: actions/upload-artifact@v4
        with:
          name: prep-build-test-flask-browserify-chrome
          path: ./dist/**/chrome

  e2e-chrome:
    needs:
      - prep-build-test-flask
    uses: ./.github/workflows/e2e-chrome.yml
    secrets:
      PR_COMMENT_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
